backend:
  name: auth0
  domain: YOUR_AUTH0_DOMAIN
  client_id: YOUR_AUTH0_CLIENT_ID
  auth_path: /.netlify/auth
  logout_path: /.netlify/logout
  site_url: https://your-site.netlify.app

media_folder: "products/media"  # where uploaded images go
public_folder: "/products/media"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Images", name: "images", widget: "list", allow_add: true, fields: [{label: "Image", name: "image", widget: "image"}] }
