backend:
  name: git-gateway
  branch: main

media_folder: "product/media"
public_folder: "/product/media"

collections:
  - name: "products"
    label: "Products"
    folder: "product"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Images", name: "images", widget: "list", allow_add: true, fields: [{label: "Image", name: "image", widget: "image"}] }
